config:
  guestbook_name: (BSP) Brunei Shell Petrolium Cloud-Native Bootcamp 
  backend_uri: "backend.minikube.local/guestbook"
image:
  repository: ernesen/frontend-bsp
  tag: "2.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  host: frontend.minikube.local
